import { Component, OnInit, signal } from '@angular/core';
import { DecimalPipe } from '@angular/common';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { PlayerApi } from '../player-api';
import { fromRouteBattleTag, toRouteBattleTag } from '../player-route';
import { PlayerStore } from '../player-store';

@Component({standalone:true,imports:[DecimalPipe,RouterLink,MatButtonModule,MatIconModule],template:`
@if(player.profile();as p){<section class="profile-head" [style.background-image]="p.namecard?'linear-gradient(90deg,#111827ee,#11182799),url('+p.namecard+')':''"><img [src]="p.avatar||'https://placehold.co/128x128/252c3a/ffffff?text=OW'" alt="Avatar"><div><span class="eyebrow">PROFIL {{p.demo?'DE DÉMONSTRATION':'PUBLIC'}}</span><h1>{{p.username}}</h1><p>{{p.battleTag}} · {{p.platform?.toUpperCase()||'Plateforme inconnue'}}</p></div><button mat-flat-button (click)="refresh()" [disabled]="loading"><mat-icon>refresh</mat-icon>{{loading?'Actualisation…':'Actualiser'}}</button></section>
<section class="metric-grid"><article><span>Temps de jeu</span><strong>{{hours(p.timePlayed)}} h</strong><small>mode compétitif</small></article><article><span>Taux de victoire</span><strong>{{p.winRate|number:'1.1-1'}} %</strong><small>{{p.gamesWon}} V · {{p.gamesLost}} D</small></article><article><span>Parties jouées</span><strong>{{p.gamesPlayed}}</strong><small>profil public</small></article></section>
<div class="section-title"><div><span class="eyebrow">COMPÉTITIF</span><h2>Rangs par rôle</h2></div></div><section class="rank-grid">@for(r of p.ranks;track r.role){<article><span class="role-icon">{{roleIcon(r.role)}}</span><div><small>{{roleName(r.role)}}</small><h3>{{r.division}} {{r.tier}}</h3></div></article>}@empty{<p class="muted">Aucun rang public disponible.</p>}</section>
<div class="section-title"><div><span class="eyebrow">PRÉFÉRENCES</span><h2>Héros les plus joués</h2></div><a [routerLink]="['/historique',routeTag(p.battleTag)]">Voir l'évolution →</a></div><section class="hero-table"><div class="table-row table-head"><span>Héros</span><span>Temps</span><span>Parties</span><span>Victoires</span><span>Taux</span></div>@for(h of p.heroes;track h.key){<div class="table-row"><strong class="hero-name"><img [src]="portrait(h.key)" [alt]="h.name" (error)="imageFallback($event)"><span>{{h.name}}</span></strong><span>{{hours(h.timePlayed)}} h</span><span>{{h.gamesPlayed}}</span><span>{{h.gamesWon}}</span><span>{{h.winRate|number:'1.0-1'}} %</span></div>}@empty{<p class="muted pad">Les statistiques par héros ne sont pas publiques.</p>}</section>
@if(error){<div class="error">{{error}}</div>}}
@else{<section class="empty"><h1>Aucun profil chargé</h1><a mat-flat-button routerLink="/">Rechercher un BattleTag</a></section>}`})
export class ProfileComponent implements OnInit {loading=false;error='';readonly portraits=signal<Record<string,string>>({});private battleTag='';constructor(readonly player:PlayerStore,private readonly api:PlayerApi,private readonly route:ActivatedRoute){} ngOnInit(){this.battleTag=fromRouteBattleTag(this.route.snapshot.paramMap.get('battleTag')??'');if(this.player.profile()?.battleTag!==this.battleTag){this.player.begin();this.api.stored(this.battleTag).subscribe({next:p=>this.player.setProfile(p),error:e=>this.player.fail(e.error?.message??'Impossible de charger ce profil.')})}this.api.heroes().subscribe({next:heroes=>this.portraits.set(Object.fromEntries(heroes.map(h=>[h.key,h.portrait])))})} portrait(key:string){return this.portraits()[key]||'https://placehold.co/80x80/252c3a/ffffff?text=OW'} imageFallback(event:Event){(event.target as HTMLImageElement).src='https://placehold.co/80x80/252c3a/ffffff?text=OW'} hours(s:number){return Math.round(s/360)/10} roleName(r:string){return ({tank:'Tank',damage:'Dégâts',support:'Soutien'} as Record<string,string>)[r]||r} roleIcon(r:string){return ({tank:'◆',damage:'⌁',support:'✚'} as Record<string,string>)[r]||'●'} routeTag(tag:string){return toRouteBattleTag(tag)} refresh(){this.loading=true;this.error='';this.player.begin();this.api.refresh(this.battleTag).subscribe({next:p=>this.player.setProfile(p),error:e=>{this.player.fail(e.error?.message??'Actualisation impossible.');this.error=this.player.error();this.loading=false},complete:()=>this.loading=false});}}
